project(
  'node_crunch2',
  'cpp',
  version: '0.0.1',
  default_options: ['cpp_std=c++23', 'warning_level=3', 'buildtype=release']
)

# Define custom warning or optimization flags
extra_flags_gcc_clang = [
  '-march=native',

  '-Wdouble-promotion',
  '-Wformat=2',
  '-Wundef',
  '-Wcast-qual',
  '-Woverloaded-virtual',
  '-Wuninitialized',
  '-Winit-self',
  '-Wredundant-decls',
  '-Wsuggest-override',
  '-Wshadow',
  '-Wnon-virtual-dtor',
  '-Wold-style-cast',
  '-Wcast-align',
  '-Wunused',
  '-Wconversion',
  '-Wsign-conversion',

  '-Wextra-semi',
  '-Wctor-dtor-privacy',
  '-Wzero-as-null-pointer-constant',
  '-Wlogical-op',
  #'-Wfloat-equal',
  '-Wpessimizing-move',
  '-Wredundant-move'
]

extra_flags_gcc = [
  '-Ofast',
  '-Walloca',
  '-Wcast-align=strict',
  '-Wimplicit-fallthrough=5',
  '-Wduplicated-cond',
  '-Wduplicated-branches',
  # '-Wuseless-cast',
  '-Wtrampolines'
]

extra_flags_clang = [
  '-O3 -ffast-math',
  '-Wimplicit-fallthrough',
  '-Wshadow-field',
  '-Wabstract-final-class',
  '-Wheader-hygiene'
]

extra_flags_msvc = [
  '/Wall',
  '/W4',
  '/w14242',
  '/w14265',
  '/w14287',
  '/we4289',
  '/w14296',
  '/w14311',
  '/utf-8'
]

# Safely check which flags are supported by the active compiler
cpp_compiler = meson.get_compiler('cpp')

if cpp_compiler.get_id() == 'gcc'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_gcc_clang + extra_flags_gcc)
elif cpp_compiler.get_id() == 'clang'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_gcc_clang + extra_flags_clang)
elif cpp_compiler.get_id() == 'msvc'
  supported_flags_lib = cpp_compiler.get_supported_arguments(extra_flags_msvc)
endif

# Point the include directory to 'src'
inc_dir = include_directories('src/nodcru2')

# Source files
sources = files(
  'src/nodcru2/nc_compression.cpp',
  'src/nodcru2/nc_config.cpp',
  'src/nodcru2/nc_encryption.cpp',
  'src/nodcru2/nc_message.cpp',
  'src/nodcru2/nc_network.cpp',
  'src/nodcru2/nc_node.cpp',
  'src/nodcru2/nc_nodeid.cpp',
  'src/nodcru2/nc_server.cpp',
  'src/nodcru2/nc_util.cpp'
)

# External dependencies:

# Import the CMake module
cmake = import('cmake')

# Configure taocpp-json as a CMake subproject
tao_json_sub = cmake.subproject('taocpp-json')
# Get the dependency target generated by CMake
tao_json_dep = tao_json_sub.dependency('taocpp-json', include_type: 'system')

# Main dependencies:
lz4_dep = dependency('lz4', fallback: ['lz4', 'lz4_dep'])
openssl_dep = dependency('openssl', fallback: ['openssl', 'openssl_dep'])
asio_dep = dependency('asio', fallback: ['asio', 'asio_dep'], include_type: 'system')
argparse_dep = dependency('argparse', fallback: ['argparse', 'argparse_dep'])
spdlog_dep = dependency('spdlog', fallback: ['spdlog', 'spdlog_dep'], include_type: 'system')
fmt_dep = dependency('fmt', fallback: ['fmt', 'fmt_dep'])

# For unit testing:
snitch_dep = dependency('snitch', fallback: ['snitch', 'snitch_dep'])

# Build the library
lib = shared_library(
  'node_crunch2',
  sources,
  include_directories: inc_dir,
  override_options: ['werror=true', 'b_lto=true'],
  cpp_args: supported_flags_lib,
  dependencies: [tao_json_dep, lz4_dep, openssl_dep, asio_dep, argparse_dep, spdlog_dep, fmt_dep],
  install: true
)

# Declare dependency for other targets/projects
node_crunch2_dep = declare_dependency(
  include_directories: inc_dir,
  link_with: lib
)

# Explicitly list header files to install them to system paths
install_headers(
  'src/nodcru2/nc_compression.hpp',
  'src/nodcru2/nc_config.hpp',
  'src/nodcru2/nc_encryption.hpp',
  'src/nodcru2/nc_exceptions.hpp',
  'src/nodcru2/nc_message.hpp',
  'src/nodcru2/nc_message_types.hpp',
  'src/nodcru2/nc_network.hpp',
  'src/nodcru2/nc_node.hpp',
  'src/nodcru2/nc_nodeid.hpp',
  'src/nodcru2/nc_server.hpp',
  'src/nodcru2/nc_util.hpp'
)

# Unit test configuration
test_sources = files(
  'tests/test_all.cpp',
  'tests/test_compression.cpp',
  'tests/test_config.cpp',
  'tests/test_encryption.cpp',
  'tests/test_message.cpp',
  'tests/test_node.cpp',
  'tests/test_nodeid.cpp',
  'tests/test_server.cpp',
  'tests/test_server_node.cpp',
  'tests/test_util.cpp'
)

test_exe = executable(
  'node_crunch2_tests',
  test_sources,
  include_directories: include_directories('src'),
  dependencies: [node_crunch2_dep, snitch_dep, tao_json_dep, asio_dep, spdlog_dep, fmt_dep],
  # override_options: ['werror=true'],
  cpp_args: supported_flags_lib
)

test('all unit tests', test_exe)
